name: Run Newman Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Newman
        run: npm install -g newman

      - name: Debug File Check
        run: ls -lah

      - name: Run Postman Collection
        run: newman run "C:\Users\Sharon Williams\Downloads\newman-testing\newman-testing\.github\workflows" -r json --reporter-json-export results.json

